apiVersion: v1
entries:
  secrets:
  - apiVersion: v2
    created: "2023-01-04T18:30:03.970893+01:00"
    description: A Helm chart to create secret files with random passwords
    digest: ff4cfb03aeaf4430eb6350aaf3a36ef0e9c246850c79bad97380778df2dc4e61
    keywords:
    - secrets
    name: secrets
    type: application
    urls:
    - https://marvkis.github.io/charts/secrets-0.1.0.tgz
    version: 0.1.0
generated: "2023-01-04T18:30:03.970512+01:00"
